kat_kem.rsp: kat
	./run

kat: Makefile rng.c rng.h randombytes.h benes.c bm.c controlbits.c decrypt.c encrypt.c gf.c operations.c pk_gen.c root.c sk_gen.c synd.c transpose.c util.c  crypto_stream_aes256ctr.c 
	./build
