#ifndef NTRUPRIME_crypto_kem_H
#define NTRUPRIME_crypto_kem_H

#include "crypto_kem_ntrulpr761.h"

#define NTRUPrime_crypto_kem_keypair crypto_kem_ntrulpr761_keypair
#define NTRUPrime_crypto_kem_enc crypto_kem_ntrulpr761_enc
#define NTRUPrime_crypto_kem_dec crypto_kem_ntrulpr761_dec
#define NTRUPrime_crypto_kem_PUBLICKEYBYTES crypto_kem_ntrulpr761_PUBLICKEYBYTES
#define NTRUPrime_crypto_kem_SECRETKEYBYTES crypto_kem_ntrulpr761_SECRETKEYBYTES
#define NTRUPrime_crypto_kem_BYTES crypto_kem_ntrulpr761_BYTES
#define NTRUPrime_crypto_kem_CIPHERTEXTBYTES crypto_kem_ntrulpr761_CIPHERTEXTBYTES
#define NTRUPRIME_CRYPTO_ALGNAME  "ntrulpr761"

#endif
